---
title: "Documentación I"
author: "Thanic Team members"
date: "10/21/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Thanic está formado por un grupo de cinco jóvenes de 19 años. Amigos de toda la vida y del mismo pueblo ahora por circunstancias personales uno de ellos vive en Amersfoort (Países Bajos) y otro de ellos en Bilbao. A pesar de ello afrontan el reto de sacar adelante este proyecto con gran ilusión.

La idea se originó un viernes de verano como una conversación más, pero pronto nos dimos cuenta de su potencial. En septiembre de ese mismo año se comenzó a organizar de froma más seria reclutando a la gente que iba a formar parte del proyecto. Y a finales de ese mes se hizo la primera reunión general. En este final de 2021 se acabará de dar forma a las ideas y se empezarán a sentar las bases de Thanic, para que en 2022 comienze la operativa. Teniendo como objetivo principal sacar una versión alpha de la aplicación antes de febrero.

# TAREAS

- [x] MVP
- [x] MAQUETACIÓN
- [ ] BUSINESS PLAN
- [ ] CREACIÓN DEL TOKEN 
- [ ] PLAN DE FINANCIACIÓN 
- [x] ENCUESTA I
- [ ] DISEÑO II
- [ ] DOCUMENTACIÓN
- [ ] DOCUMENTO ESTADÍSTICO
- [ ] RESEARCH CONCURSOS PÚBLICOS/PRIVADOS
- [ ] PRESENTACIÓN FORMAL (2-4 PAGS)

---

# REUNIONES 

## Reunión I 30/09/2021

Esta fue la primera reunión que hicimos. Se explicó el proyecto y se repartieron las tareas de cada uno.
Como tarea se mandó que cada uno pensara y apuntara dos ideas más.

## Reunión II 04/10/2021

La reunión comenzó con un brainstorming ya que las ideas que se trajeron preparadas no eran suficientes.  La más destacada fue el sistema de avatares NFTs, ya que puede ser una buena forma de además de dar cierta exclusividad a ciertos usuarios, sacar rentabilidad a la aplicación. A parte de que esto va de la mano con la tecnología que queremos implementar.

## Reunión III 14/10/2021

Comenzó hablando sobre que el proyecto es serio y falta profesionalidad y compromiso por parte de alguno de los miembros. Después se editaron, redistribuyeron y añadieron tareas como el plan de financiación. De este además se habló de que se publicará en más de una plataforma como Indiegogo o Kickstarter, con un objetivo de aproximadamente 10.000€ de contribuciones. Por último se discutió a donde iba a ir el dinero. Mayormente irá a nuestro depósito de Ethreum para que la aplicación pueda funcionar y queda por determinar si parte de las donaciones irán dirigidas a sueldos.


## Reunión IV 20/10/2021


### Financiación



Búsqueda avanzada de diversos métodos para obtener financiación, **concurso público/privado**, **crowfunding**, business angels...

- Presentación formal proyecto detallado no técnico (2-4 páginas)
- Elaboración material gráfico para acompañar la presentación
- Estimación del capital objetivo y predicción de la financiación
- Research concursos público/privados
- Elaboración material audiovisual para apoyar imagen de marca así como explicación de elementos complejos (Material didáctico)
- Realización de presupuesto variabe en función de tramos en la financiación (Tramificado)
- Sistema de recompensa a los integrantes en función objetivos-tiempo
- Gestión estructural del proyecto
- Documento datos estadísticos básicos

### Marketing y Comunicación

#### 1. Objetivo:

Conseguir llegar a un gran número de personas, tanto público objetivo como público conversible

#### 2. Tareas:

- Elaborar perfil cliente objetivo, público objetivo y público convertible
- Elaboración contenido gráfico y audiovisual genérico para dispersión general en cualquier método/plataforma
- Publicación y actualización de documentación oficial (Diario + ChangeLog)

#### 3. Marketing Orgánico

- Creación plataformas digitales (Tik-Tok, Instagram, Github, LinkedIn)
- Publicación recurrente y programada de contenido
- Creación de contenido didáctico (++ Engagement)
- Proyecto + documentación Github
- Interacción activa con otros proyectos, personas y perfiles de interés
- Comunicación oficial (++ Boca a Boca)

#### 4. Marketing Inorgánico

- Publicación en foros relacionados (Soft bombing)
- Conseguir visibilidad en prensa
- Sistema Early Acces(Beta-Testnet) + Sistemas de Rewards

### Plan de desarrollo Tecnológico

#### Stage 1

##### APP (M.V.P)

- Elección de Framework Front-End, así como el estudio activo de este
- Desarrollo de funcionalidades M.V.P
- Implenmentación del Front-End con el diseño (M.V.P)
- Deploy de caracteristicas básicas

##### APP (Ideas)

- Añadir caracteristicas extra
- Implementación Front-End Avanzado

##### TOKEN ($THC)

- Elección de la tecnología y red base para emprender el estudio y planificación
- Investigación y estudio activo tecnología elegida


- Planificación detallada hoja de ruta del desarrollo a base de capas

---

# Actividad

## 24/10/2021 Inicio web proyecto (@Jon)

Hoy da comienzo la primera materialización del proyecto, dando inicio a la creación de la página web explicativa del proyecto así como la creación del proyecto en github y su primera difusión. Roadmap:

- [x] Creación del proyecto en **Github** ([https://github.com/Thanic-app/Thanic](url))
- [ ] Diseño y programación página web
- [ ] Elaboración **documento base** que se trasladará al diseño
- [ ] Creación redes sociales (Así como **contenido base**)
- [ ] Elaboración **README**